name: app_python
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up python
              uses: actions/setup-python@v4
              with:
                python-version: '3.8'
            - name: Install dependencies
              working-directory: ./app_python
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Running unit tests
              working-directory: ./app_python
              run: |
                pip install pytest
                pytest
            - name: Lint with Ruff
              working-directory: ./app_python
              run: |
                pip install ruff
                ruff --output-format=github .